server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/blas
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
blas:
  aliasBlasPrivateKey: blasSecretKey
  certificate: BlasSecretKey.p12
  service:
    serviceName: blas-payment-gateway
  gate-interceptor:
    enableLogRequest: true
    enableLogLocalRequest: false
  blas-service-support:
    throughServiceSupport: true
    endpointCheckMaintenance: http://localhost:8084/maintenance/check
  blas-idp:
    isSendEmailAlert: false
    jwt:
      timeToExpiredInternalToken: 120 #2 minutes
  blas-payment-gateway:
    vnpay:
      version: 2.1.0
      tmnCode: RHC8EX66
      payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      returnUrl: http://localhost:8083
      checkOrderUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
      vnpTxnRefLength: 8
      orderType: other
    lengthOfId: 10

#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.blas: DEBUG
