apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-service-config
data:
  application.yaml: |
    server:
      port: {{ .Values.service.targetPort }}
    spring:
      profiles:
        active: {{ index .Values "service-config" "spring" "profile" }}
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${mysql-url}
        username: ${mysql-username}
        password: ${mysql-password}
      data:
        mongodb:
          uri: ${mongodb-url}
      jpa:
        hibernate:
          ddl-auto: none
        open-in-view: false
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          probes:
            enabled: true

    blas:
      aliasBlasPrivateKey: {{ index .Values "service-config" "blas" "aliasBlasPrivateKey" }}
      certificate: {{ index .Values "service-config" "blas" "certificate" }}
      service:
        serviceName: {{ .Chart.Name }}
      blas-service-support:
        throughServiceSupport: {{ index .Values "service-config" "blas" "blas-service-support" "throughServiceSupport" }}
        endpointCheckMaintenance: {{ index .Values "service-config" "blas" "blas-service-support" "endpointCheckMaintenance" }}
      blas-idp:
        isSendEmailAlert: {{ index .Values "service-config" "blas" "blas-idp" "isSendEmailAlert" }}
      blas-payment-gateway:
        stripePrivateKey: ${stripe-private-key}
        vnpay:
          version: {{ index .Values "service-config" "blas" "blas-payment-gateway" "vnpay" "version" }}
          privateKey: ${vnpay-private-key}
          tmnCode: ${vnpay-tmn-code}
          payUrl: {{ index .Values "service-config" "blas" "blas-payment-gateway" "vnpay" "payUrl" }}
          returnUrl: {{ index .Values "service-config" "blas" "blas-payment-gateway" "vnpay" "returnUrl" }}
          checkOrderUrl: {{ index .Values "service-config" "blas" "blas-payment-gateway" "vnpay" "checkOrderUrl" }}
          vnpTxnRefLength: {{ index .Values "service-config" "blas" "blas-payment-gateway" "vnpay" "vnpTxnRefLength" }}
          orderType: {{ index .Values "service-config" "blas" "blas-payment-gateway" "vnpay" "orderType" }}
        lengthOfId: {{ index .Values "service-config" "blas" "blas-payment-gateway" "lengthOfId" }}
      hazelcast:
        aksNamespace: {{ .Values.aksNamespace }}
        hazelcastService: {{ .Values.hazelcastService }}

    logging:
      level:
{{- range $key, $value := index .Values "service-config" "logging" "level" }}
        {{ $key }}: {{ $value }}
{{- end }}

  hazelcast-client.yaml: |-
    hazelcast-client:
      network:
        kubernetes:
          enabled: {{ index .Values "service-config" "hazelcast-client" "network" "kubernetes" "enabled" }}

  bootstrap.yaml: |-
    spring:
      cloud:
        vault:
          authentication: KUBERNETES
          kubernetes:
            role: {{ index .Values "service-config" "vault" "kubernetes" "role" }}
            service-account-token-file: {{ index .Values "service-config" "vault" "kubernetes" "service-account-token-file" }}
          uri: {{ index .Values "service-config" "vault" "uri" }}
          namespace: {{ index .Values "service-config" "vault" "namespace" }}
          kv:
            backend: {{ index .Values "service-config" "vault" "kv" "backend" }}
            application-name: {{ index .Values "service-config" "vault" "kv" "application-name" }}
            default-context: {{ index .Values "service-config" "vault" "kv" "default-context" }}
          enabled: {{ index .Values "service-config" "vault" "enabled" }}
          connection-timeout: {{ index .Values "service-config" "vault" "connection-timeout" }}
          read-timeout: {{ index .Values "service-config" "vault" "read-timeout" }}
